name: Update profile README

on:
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *' # Daily at 06:17 UTC
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate repository list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_USERNAME: Kwts30
          # Set one of the following:
          REPO_LIST_LIMIT: 1              # show the most recently updated repo
          # FEATURED_REPO: my-repo-name   # OR show this exact repo by name (uncomment and set)
        run: |
          node -v
          node script/generate-repo-list.mjs

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update featured repository list"
            git push
          else
            echo "No changes to commit"
          fi
